<?xml version="1.0" encoding="windows-1256"?>

<!DOCTYPE collection [
	<!ELEMENT collection (item)>
	<!ELEMENT item (english, arabic)>
	<!ELEMENT english (#PCDATA)>
	<!ELEMENT arabic (#PCDATA)>
	]
>

<collection>
	<item>
		<english>Word</english>
		<arabic>ﬂ·„…</arabic>
	</item>
	<item>
		<english>Book</english>
		<arabic>ﬂ »</arabic>
	</item>
	<item>
		<english>School</english>
		<arabic>„œ—”…</arabic>
	</item>
	<item>
		<english>Scholar</english>
		<arabic>⁄«·„</arabic>
	</item>
	<item>
		<english>Paradise</english>
		<arabic>Ã‰…</arabic>
	</item>
	<item>
		<english>Fire</english>
		<arabic>‰«—</arabic>
	</item>
</collection>